library(ggplot2)
library(RColorBrewer)
library(reshape2)
library(tikzDevice)
colours <- brewer.pal(n = 7, name = "Dark2")
powerFormatter <- function(x)
{
	xAsCharacter <- as.character(x)
	#xAsCharacter <- sapply(xAsCharacter, function(y) if(nchar(y) == 2) paste0(y, ".0") else y)
	paste0("$10^{", xAsCharacter, "}$")
}
source("./generateScenarios.R")
load("./summarised.RData")

scenarios$epsilon <- factor(as.character(scenarios$epsilon), levels = as.character(sort(unique(scenarios$epsilon), decreasing = TRUE)))
timeData <- melt(cbind(scenarios, time = times), measure.vars = "time")
timeSingleSampleData <- melt(cbind(scenarios, timeSingleSample = timeSingleSample), measure.vars = "timeSingleSample")
averageEstimatesData <- melt(cbind(scenarios, averageEstimate = averageEstimates), measure.vars = "averageEstimate")
workNormalizedSingleSampleVarianceData <- melt(cbind(scenarios, workNormalizedSingleSampleVariance = workNormalizedSingleSampleVariance), measure.vars = "workNormalizedSingleSampleVariance")
varianceDataSingleSample <- melt(cbind(scenarios, varianceSingleSample = varianceSingleSample), measure.vars = "varianceSingleSample")
nCapacityLevels <- unique(scenarios$nCapacities)

setwd("plots")
for(nCapacityLevels in nCapacityLevels)
{
	demands <- unique(subset(scenarios, nCapacities == nCapacityLevels)$demand)
	for(currentDemand in demands)
	{
		currentTimeData <- subset(timeData, nCapacities == nCapacityLevels & demand == currentDemand)
		timePlot <- ggplot(data=currentTimeData, aes(x = epsilon, y = value, group = method, colour = method)) + guides(col=guide_legend(ncol = 2, title=NULL)) + ggtitle(paste0("Demand = ", currentDemand, ", Capacity levels = ", nCapacityLevels)) + ylab("Seconds") + xlab("epsilon") + geom_line() + scale_colour_manual(values = colours) + scale_x_discrete(name = "epsilon") + theme(legend.position = c(0.77, 0.9))
		pdf(paste0("./times-", nCapacityLevels, "-", currentDemand, ".pdf"))
			print(timePlot)
		dev.off()

		currentTimeSingleSampleData <- subset(timeSingleSampleData, nCapacities == nCapacityLevels & demand == currentDemand)
		timePlot <- ggplot(data=currentTimeSingleSampleData, aes(x = epsilon, y = value, group = method, colour = method)) + guides(col=guide_legend(ncol = 2, title=NULL)) + ggtitle(paste0("Demand = ", currentDemand, ", Capacity levels = ", nCapacityLevels)) + ylab("Seconds") + xlab("epsilon") + geom_line() + scale_colour_manual(values = colours) + scale_x_discrete(name = "epsilon") + theme(legend.position = c(0.77, 0.9))
		pdf(paste0("./timeSingleSample", nCapacityLevels, "-", currentDemand, ".pdf"))
			print(timePlot)
		dev.off()

		currentAverageEstimatesData <- subset(averageEstimatesData, nCapacities == nCapacityLevels & demand == currentDemand)
		estimatesPlot <- ggplot(data=currentAverageEstimatesData, aes(x = epsilon, y = log10(value), group = method, colour = method)) + guides(col=guide_legend(ncol = 2, title=NULL)) + xlab("epsilon") + ylab("Estimate") + geom_line() + scale_colour_manual(values = colours) + scale_x_discrete(name = "epsilon") + theme(legend.position = c(0.77, 0.9)) + scale_y_continuous(labels = powerFormatter) + ggtitle("Average estimates")
		texFile <- paste0("./estimates-", nCapacityLevels, "-", currentDemand, ".tex")
		tikz(texFile, width = 7, height = 7, standAlone = TRUE, packages = c("\\usepackage{amssymb}", "\\usepackage{tikz}", "\\usepackage[active,tightpage,psfixbb]{preview}", "\\PreviewEnvironment{pgfpicture}", "\\setlength\\PreviewBorder{0pt}"))
			print(estimatesPlot)
		dev.off()
		system(paste0("pdflatex ", texFile))
		unlink(paste0("./estimates-", nCapacityLevels, "-", currentDemand, ".tex"))
		unlink(paste0("./estimates-", nCapacityLevels, "-", currentDemand, ".aux"))
		unlink(paste0("./estimates-", nCapacityLevels, "-", currentDemand, ".log"))

		currentWorkNormalizedSingleSampleVarianceData <- subset(workNormalizedSingleSampleVarianceData, nCapacities == nCapacityLevels & demand == currentDemand & method != "crudeMC")
		workNormalizedSingleSampleVariancePlot <- ggplot(data=currentWorkNormalizedSingleSampleVarianceData, aes(x = epsilon, y = log10(value), group = method, colour = method)) + guides(col=guide_legend(ncol = 2, title=NULL)) + xlab("epsilon") + ylab("Work Normalized Variance Per Sample") + geom_line() + scale_colour_manual(values = colours) + scale_x_discrete(name = "epsilon") + theme(legend.position = c(0.77, 0.9)) + scale_y_continuous(labels = powerFormatter) + ggtitle("Work Normalized Variances Per Sample")
		texFile <- paste0("./workNormalizedSingleSampleVariance-", nCapacityLevels, "-", currentDemand, ".tex")
		tikz(texFile, width = 7, height = 7, standAlone = TRUE, packages = c("\\usepackage{amssymb}", "\\usepackage{tikz}", "\\usepackage[active,tightpage,psfixbb]{preview}", "\\PreviewEnvironment{pgfpicture}", "\\setlength\\PreviewBorder{0pt}"))
			print(workNormalizedSingleSampleVariancePlot)
		dev.off()
		system(paste0("pdflatex ", texFile))
		unlink(paste0("./workNormalizedSingleSampleVariance-", nCapacityLevels, "-", currentDemand, ".tex"))
		unlink(paste0("./workNormalizedSingleSampleVariance-", nCapacityLevels, "-", currentDemand, ".aux"))
		unlink(paste0("./workNormalizedSingleSampleVariance-", nCapacityLevels, "-", currentDemand, ".log"))

		currentVarianceDataSingleSample <- subset(varianceDataSingleSample, nCapacities == nCapacityLevels & demand == currentDemand & method != "crudeMC")
		varianceDataSingleSamplePlot <- ggplot(data=currentVarianceDataSingleSample, aes(x = epsilon, y = log10(value), group = method, colour = method)) + guides(col=guide_legend(ncol = 2, title=NULL)) + xlab("epsilon") + ylab("Variance Per Sample") + geom_line() + scale_colour_manual(values = colours) + scale_x_discrete(name = "epsilon") + theme(legend.position = c(0.77, 0.9)) + scale_y_continuous(labels = powerFormatter) + ggtitle("Variances Per Sample")
		texFile <- paste0("./varianceSingleSample-", nCapacityLevels, "-", currentDemand, ".tex")
		tikz(texFile, width = 7, height = 7, standAlone = TRUE, packages = c("\\usepackage{amssymb}", "\\usepackage{tikz}", "\\usepackage[active,tightpage,psfixbb]{preview}", "\\PreviewEnvironment{pgfpicture}", "\\setlength\\PreviewBorder{0pt}"))
			print(varianceDataSingleSamplePlot)
		dev.off()
		system(paste0("pdflatex ", texFile))
		unlink(paste0("./varianceSingleSample-", nCapacityLevels, "-", currentDemand, ".tex"))
		unlink(paste0("./varianceSingleSample-", nCapacityLevels, "-", currentDemand, ".aux"))
		unlink(paste0("./varianceSingleSample-", nCapacityLevels, "-", currentDemand, ".log"))

	}
}
setwd("..")
